version: "3"

services:
  db:
    image: postgres
    container_name: pg
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password

  cache:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  web:
    build: .
    container_name: accesshandler
    links:
      - db
      - cache
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - ./:/usr/local/accesshandler

